version: '3.8'
services:
  backend:
    image: server:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/test_task_db

  db:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_task_db
    healthcheck:
      test: "pg_isready -U user -d test_task_db"
      interval: "10s"
      timeout: "5s"
      retries: 5
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './server.conf:/etc/nginx/sites-enabled/server.conf'
volumes:
  postgres-data: