scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["10.5.0.1:8181"]
    metrics_path: "/actuator/prometheus"
  - job_name: "keycloak"
    static_configs:
      - targets: ["10.5.0.7:8080"]
    metrics_path: "/realms/TestCompanyRealm/metrics"